[package]
name = "elvis"
version = "0.2.0"
edition = "2021"

[dependencies]
elvis-core = { path = "../elvis-core" }
tokio = { version = "1.23.0", features = ["rt", "rt-multi-thread", "time", "macros", "sync"] }
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "1.0.37"
clap = { version = "4.0.18", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.4.0", features = [ "async_tokio", "html_reports" ] }
anyhow = "1.0.66"

[[bench]]
name = "benchmarks"
harness = false