name: basic-ci
# program runs every time there is a push to the repository
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # set the default working directory to sim so it can find the Cargo.toml file
    defaults:
      run: 
        working-directory: ./sim 
        
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy 
      run: cargo clippy
  test-on-mac: 
    runs-on: macos-latest
    defaults:
      run: 
        working-directory: ./sim 
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
