
name: push-to-docs-repo
on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  push-docs:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sim
    steps:
    - name: Run rustdoc
      run: cargo doc --target-dir target

  
