on:
  push
  
jobs:
  push:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cs-wwu/srg-elvis-docs
          ref: 'main'
          #token:  ${{ secrets.BOT_KEY }}
      - name: setup git config
        run: |
          git config user.name "Bot"
          git config user.email "bot@bot.com"
      #- run: git push origin main
  
